/*
 * Copyright 2010-2023 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.swiftexport;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("plugins/swift-export/testData")
@TestDataPath("$PROJECT_ROOT")
public class Kotlin2SwuftExportCompilerPluginTest extends AbstractKotlin2SwiftExportContextTest {
    @Test
    @TestMetadata("javaAnnotationWithInnerEnum.kt")
    public void testSimple() throws Exception {
        runTest("plugins/swift-export/testData/simple.kt");
    }
}
